name: Génération du PDF

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: docker://pandoc/core:2.9
        with:
          args: "-f commonmark -o /github/workspace/statuts.pdf /github/workspace/statuts.md" # gets appended to pandoc command
